#!/bin/sh

. /lib/lsb/init-functions

NAME=logstash
LOG_DIR=/var/log/$NAME

mkdir -p "$LOG_DIR" 

sv start elasticsearch || exit 1
sv start rabbitmq || exit 1

log_daemon_msg "Starting Logstash"

RUN_COMMAND="/opt/logstash-1.4.2/bin/logstash -f /etc/logstash/logstash.conf"

exec $RUN_COMMAND >> $LOG_DIR/logstash.log 2>&1

log_end_msg $?

exit 0